export function cap(s) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

const SKILL_LABELS = {
  attack: "Attack",
  strength: "Strength",
  defence: "Defence",
  ranged: "Ranged",
  magic: "Magic",
  prayer: "Prayer",
  runecrafting: "Runecraft",
  construction: "Construction",
  hitpoints: "Hitpoints",
  agility: "Agility",
  herblore: "Herblore",
  thieving: "Thieving",
  crafting: "Crafting",
  fletching: "Fletching",
  slayer: "Slayer",
  hunter: "Hunter",
  mining: "Mining",
  smithing: "Smithing",
  fishing: "Fishing",
  cooking: "Cooking",
  firemaking: "Firemaking",
  woodcutting: "Woodcutting",
  farming: "Farming",
  sailing: "Sailing",
};

const BOSS_LABELS = {
  abyssal_sire: "Abyssal Sire",
  alchemical_hydra: "Alchemical Hydra",
  amoxliatl: "Amoxliatl",
  araxxor: "Araxxor",
  artio: "Artio",
  barrows_chests: "Barrows Chests",
  brutus: "Brutus",
  bryophyta: "Bryophyta",
  callisto: "Callisto",
  calvarion: "Calvar'ion",
  cerberus: "Cerberus",
  chambers_of_xeric: "Chambers of Xeric",
  chambers_of_xeric_challenge_mode: "Chambers of Xeric: Challenge Mode",
  chaos_elemental: "Chaos Elemental",
  chaos_fanatic: "Chaos Fanatic",
  commander_zilyana: "Commander Zilyana",
  corporeal_beast: "Corporeal Beast",
  crazy_archaeologist: "Crazy Archaeologist",
  dagannoth_prime: "Dagannoth Prime",
  dagannoth_rex: "Dagannoth Rex",
  dagannoth_supreme: "Dagannoth Supreme",
  deranged_archaeologist: "Deranged Archaeologist",
  doom_of_mokhaiotl: "Doom of Mokhaiotl",
  duke_sucellus: "Duke Sucellus",
  general_graardor: "General Graardor",
  giant_mole: "Giant Mole",
  grotesque_guardians: "Grotesque Guardians",
  hespori: "Hespori",
  kalphite_queen: "Kalphite Queen",
  king_black_dragon: "King Black Dragon",
  kraken: "Kraken",
  kreearra: "Kree'arra",
  kril_tsutsaroth: "K'ril Tsutsaroth",
  lunar_chests: "Lunar Chests",
  mimic: "Mimic",
  nex: "Nex",
  nightmare: "The Nightmare",
  phosanis_nightmare: "Phosani's Nightmare",
  obor: "Obor",
  phantom_muspah: "Phantom Muspah",
  sarachnis: "Sarachnis",
  scorpia: "Scorpia",
  scurrius: "Scurrius",
  shellbane_gryphon: "Shellbane Gryphon",
  skotizo: "Skotizo",
  sol_heredit: "Sol Heredit",
  spindel: "Spindel",
  tempoross: "Tempoross",
  the_corrupted_gauntlet: "The Corrupted Gauntlet",
  the_gauntlet: "The Gauntlet",
  the_hueycoatl: "The Hueycoatl",
  the_leviathan: "The Leviathan",
  the_royal_titans: "The Royal Titans",
  the_whisperer: "The Whisperer",
  theatre_of_blood: "Theatre of Blood",
  theatre_of_blood_hard_mode: "Theatre of Blood: Hard Mode",
  thermonuclear_smoke_devil: "Thermonuclear Smoke Devil",
  tombs_of_amascut: "Tombs of Amascut",
  tombs_of_amascut_expert: "Tombs of Amascut: Expert Mode",
  tzkal_zuk: "TzKal-Zuk",
  tztok_jad: "TzTok-Jad",
  vardorvis: "Vardorvis",
  venenatis: "Venenatis",
  vetion: "Vet'ion",
  vorkath: "Vorkath",
  wintertodt: "Wintertodt",
  yama: "Yama",
  zalcano: "Zalcano",
  zulrah: "Zulrah",
};

export function bossLabel(b) {
  return BOSS_LABELS[b] || b.replace(/_/g, " ").replace(/\b\w/g, c => c.toUpperCase());
}

export function skillLabel(s) {
  return SKILL_LABELS[s] || cap(s);
}
